package com.secondexample.HappyWalk;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

@Controller//This means that this class is a Controller
@RequestMapping(path="/demo")//
public class AdminController {
    @Autowired//to get the bean called userRepository
    //which is auto-generated by Spring, use it to handle the data
    private UserRepository userRepository;

    //---------------- show all users in JSON -----------------------
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers(){
        //This returns a JSON or XML with the user
        return userRepository.findAll();
    }
    //---------------- show all users -----------------------
    @GetMapping("/listAllTheUsers")
    public ModelAndView getAlltheUsers(){
        ModelAndView mav = new ModelAndView("list-users");
        mav.addObject("users", userRepository.findAll());
        return mav;
    }
    //---------------- add user form -----------------------
    @GetMapping("/addUserForm")
    public ModelAndView addUserForm(){
        ModelAndView mav = new ModelAndView("add-user-form");
        User user = new User();
        mav.addObject("user", user);
        return mav;
    }
    //---------------- save user -----------------------
    @PostMapping("/saveUser")
    public String saveUser(@ModelAttribute User user){

        userRepository.save(user);
        //return "redirect:/demo/all";
        return "redirect:/demo/listAllTheUsers";
    }



}
